# Secret Definitions for OctoLLM
# This file documents all secrets needed (NEVER include actual secret values)

secrets:
  # LLM API Keys
  - name: openai-api-key
    description: OpenAI API key for GPT-4 calls
    type: api-key
    rotation_policy: 90-days
    rotation_automation: manual
    access:
      - orchestrator
      - planner-arm
    storage: gcp-secret-manager

  - name: anthropic-api-key
    description: Anthropic Claude API key
    type: api-key
    rotation_policy: 90-days
    rotation_automation: manual
    access:
      - orchestrator
      - coder-arm
    storage: gcp-secret-manager

  # Database Credentials
  - name: postgres-admin-password
    description: PostgreSQL admin user password
    type: password
    rotation_policy: 30-days
    rotation_automation: automated  # Cloud SQL can auto-rotate
    access:
      - database-operators
    storage: gcp-secret-manager

  - name: postgres-app-password
    description: PostgreSQL application user password
    type: password
    rotation_policy: 30-days
    rotation_automation: automated
    access:
      - orchestrator
      - all-arms
    storage: gcp-secret-manager

  # Redis Credentials
  - name: redis-auth-string
    description: Redis authentication string
    type: password
    rotation_policy: 30-days
    rotation_automation: automated  # Memorystore can auto-rotate
    access:
      - orchestrator
      - all-arms
    storage: gcp-secret-manager

  # TLS Certificates
  - name: tls-certificates
    description: TLS certificates for ingress
    type: certificate
    rotation_policy: automated-cert-manager
    rotation_automation: automated  # cert-manager handles renewal
    access:
      - ingress-controller
    storage: kubernetes-secrets  # cert-manager managed

  # Service Account Keys
  - name: gcp-service-account-key
    description: GCP service account key for CI/CD
    type: service-account-key
    rotation_policy: 90-days
    rotation_automation: manual
    access:
      - github-actions
      - gitlab-ci
    storage: github-secrets  # Or GitLab variables

  # Monitoring & Alerting
  - name: slack-webhook-url
    description: Slack webhook for alerts
    type: webhook
    rotation_policy: as-needed
    rotation_automation: manual
    access:
      - monitoring-system
    storage: gcp-secret-manager

# Secret Naming Convention
naming_convention:
  format: "{environment}-{service}-{secret-type}"
  examples:
    - prod-octollm-postgres-password
    - dev-octollm-openai-api-key
    - staging-octollm-redis-auth

# Secret Storage Backends
storage_backends:
  gcp_secret_manager:
    project_id: octollm-{environment}
    location: global
    replication: automatic
    encryption: google-managed

  kubernetes_secrets:
    namespace: octollm-{environment}
    encryption_at_rest: true
    type: Opaque

# Access Control
access_control:
  principle: least-privilege
  method: workload-identity  # GCP
  audit_logging: enabled
  review_frequency: quarterly

# Rotation Procedures
rotation_procedures:
  automated:
    - Cloud SQL auto-rotation (via Terraform)
    - cert-manager certificate renewal
    - Kubernetes service account tokens (auto-rotate every 90 days)

  manual:
    - API keys (OpenAI, Anthropic)
    - Service account keys (GCP, GitHub)
    - Webhook URLs

  emergency:
    - Immediate rotation if compromised
    - Incident response team notification
    - Security audit trigger

# Security Best Practices
security:
  - NEVER commit secrets to git (use .gitignore)
  - Use pre-commit hooks (gitleaks) to prevent accidental commits
  - Encrypt secrets at rest (Google-managed or customer-managed keys)
  - Encrypt secrets in transit (TLS 1.2+)
  - Audit all secret access (Cloud Audit Logs)
  - Rotate secrets regularly (automated when possible)
  - Use Workload Identity (no service account keys in Kubernetes)
  - Principle of least privilege (each service accesses only needed secrets)
  - Monitor for secret exfiltration (DLP, anomaly detection)
