# External Secrets Operator Configuration
# Syncs secrets from GCP Secret Manager to Kubernetes Secrets

# Install External Secrets Operator:
# helm repo add external-secrets https://charts.external-secrets.io
# helm install external-secrets external-secrets/external-secrets \
#   --namespace external-secrets-system \
#   --create-namespace

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: octollm-dev
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@octollm-dev.iam.gserviceaccount.com

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: octollm-dev
spec:
  provider:
    gcpsm:
      projectID: "octollm-dev"
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: octollm-dev-cluster
          serviceAccountRef:
            name: external-secrets-sa

---
# Example: Sync OpenAI API Key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openai-api-key
  namespace: octollm-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: openai-api-key  # Kubernetes Secret name
    creationPolicy: Owner
  data:
    - secretKey: api-key  # Key in Kubernetes Secret
      remoteRef:
        key: dev-octollm-openai-api-key  # Key in GCP Secret Manager

---
# Example: Sync PostgreSQL Password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: octollm-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: dev-octollm-postgres-username
    - secretKey: password
      remoteRef:
        key: dev-octollm-postgres-password
    - secretKey: host
      remoteRef:
        key: dev-octollm-postgres-host
    - secretKey: database
      remoteRef:
        key: dev-octollm-postgres-database

---
# Example: Sync Redis Auth String
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: octollm-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: auth-string
      remoteRef:
        key: dev-octollm-redis-auth
    - secretKey: host
      remoteRef:
        key: dev-octollm-redis-host
    - secretKey: port
      remoteRef:
        key: dev-octollm-redis-port
